name: Blue-Green Switch
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '¿A qué ambiente cambiar?'
        required: true
        default: 'green'
        type: choice
        options:
          - green
          - blue

jobs:
  switch:
    runs-on: self-hosted
    steps:
      - name: Conmutar tráfico en Nginx
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i $HOME/.ssh/github_actions \
            ${{ secrets.NGINX_USER }}@10.0.1.3 \
            "if [ '${{ github.event.inputs.environment }}' = 'green' ]; then
              sudo /usr/local/bin/switch-green.sh
            else
              sudo /usr/local/bin/switch-blue.sh
            fi"

      - name: Verificar header de respuesta
        run: |
          sleep 3
          curl -sI http://10.0.1.3 | grep X-Deployment-Color
