name: K6 Load Test CI

on:
  push:
    branches: [ "main" ]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg
          curl https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6

      - name: Run K6 Cloud Test
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: |
          k6 login cloud --token $K6_CLOUD_TOKEN
          k6 cloud load-test.js